// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgxz7hGT1ZUS0yBf6wX07HAwuy93zDbsQ',
    appId: '1:757515336429:web:ead9dc665b17f10a6daae4',
    messagingSenderId: '757515336429',
    projectId: 'workouttracker-yongsan2026',
    authDomain: 'workouttracker-yongsan2026.firebaseapp.com',
    storageBucket: 'workouttracker-yongsan2026.firebasestorage.app',
    measurementId: 'G-4S4C43P4R0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3124OoTXSmsSkiuu1czpP_7UVN2INQu4',
    appId: '1:757515336429:android:af35ceb3a373de366daae4',
    messagingSenderId: '757515336429',
    projectId: 'workouttracker-yongsan2026',
    storageBucket: 'workouttracker-yongsan2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7RkWmXRTLv7iFwtrOXZNsBYZcZGcADdg',
    appId: '1:757515336429:ios:e1a827062ce5eb556daae4',
    messagingSenderId: '757515336429',
    projectId: 'workouttracker-yongsan2026',
    storageBucket: 'workouttracker-yongsan2026.firebasestorage.app',
    iosBundleId: 'com.modoo.workoutTracker2026',
  );

}